Setup basic functionality
cuappdev/announcements-backend-old pull request #1
Opened 2019-10-29 02:23 UTC by seancorc

## Overview

- Add routes for creating, deleting, updating the expiration date, and getting the active announcements, if any (An announcement is active if its expiration date is after the current date). 
- Add basic announcement table schema.

## Test Coverage

I tested each route using Postman.

## Next Steps
1. Implement the ability to specify which iOS/Android apps the announcement should be presented on (e.g. not announcing eatery specific info on transit). 
2. Create an API doc for iOS/Android devs.

</details>

2019-10-29 02:56 UTC, manishsaha requested changes

2019-10-29 02:56 UTC, sahamanish99 commented on app.py
> +db_filename = "annoucement.db"
should be announcements.db

2019-10-29 02:56 UTC, sahamanish99 commented on app.py
> +from datetime import datetime
alphabetize

2019-10-29 02:56 UTC, sahamanish99 commented on app.py
> +SUCCESFUL_RESPONSE = json.dumps({"success": True})
this should probably go in a constants file

2019-10-29 02:56 UTC, sahamanish99 commented on app.py
> +def create_announcment():
announcement*

2019-10-29 02:56 UTC, sahamanish99 commented on app.py
> +SUCCESFUL_RESPONSE = json.dumps({"success": True})
SUCCESSFUL*

2019-10-29 02:56 UTC, sahamanish99 commented on app.py
> +    return SUCCESFUL_RESPONSE, 200
SUCCESSFUL*

2019-10-29 02:56 UTC, sahamanish99 commented on app.py
> +@app.route("/update_expiration_date/", methods=["PUT"])
I'm not sure if we use any PUT methods in any of our endpoints, maybe this should just be a POST? would confirm with others tho

2019-10-29 02:56 UTC, sahamanish99 commented on app.py
> +    return SUCCESFUL_RESPONSE, 200
typo, as above

2019-10-29 02:56 UTC, sahamanish99 commented on app.py
> +    db.session.delete(announcment)
announcement*

2019-10-29 02:56 UTC, sahamanish99 commented on app.py
> +    return SUCCESFUL_RESPONSE, 200
typo here too

2019-10-29 02:56 UTC, sahamanish99 commented on app.py
> +    if active_announcements == []:
you can probably just check `if not active_announcements`

2019-10-29 02:56 UTC, sahamanish99 commented on app.py
> +    app.run(host="0.0.0.0", port=5000, debug=True)
def create environment variables for port, filenames, etc

2019-10-29 04:40 UTC, seancorc commented on app.py
> +    return SUCCESFUL_RESPONSE, 200
Thanks for feedback, I really need to learn how to spell lol.

2019-10-29 05:00 UTC, seancorc commented on app.py
> +@app.route("/update_expiration_date/", methods=["PUT"])
I think this is actually supposed to be PATCH as "The PATCH method requests that a set of changes described in the request entity be applied to the resource identified by the Request- URI." (https://tools.ietf.org/html/rfc5789). 

It should work as intended either way so fine to change it if desired.

2019-10-29 05:01 UTC, meganle reviewed
Can we also add the black linting with the precommit hook? @sahamanish99 can help you with this!

2019-10-30 21:20 UTC, kq-li requested changes

2019-10-30 21:20 UTC, kq-li commented on app.py
> +    subject = post_body.get("subject")
should add a way to fail gracefully if any of these fields are not included

2019-10-30 21:20 UTC, kq-li commented on app.py
> +@app.route("/update_expiration_date/", methods=["PUT"])
prefer calling this route `/update/` and having a way to update the other fields as well

2019-10-30 21:20 UTC, kq-li commented on app.py
> +    name = post_body.get("name")
incorporate ID here instead of name (and maybe make it a route parameter)

2019-10-30 21:20 UTC, kq-li commented on app.py
> +    # Name is an identifier, so there should not be any duplicates.
i think it might be better to actually generate an ID and not treat name as a primary key here

2019-10-30 21:20 UTC, kq-li commented on app.py
> +@app.route("/delete/<name>/", methods=["DELETE"])
ID again

2019-10-30 21:20 UTC, kq-li commented on app.py
> +@app.route("/get_announcements/", methods=["GET"])
i prefer `/active/`, and you don't need to include the methods if it's just GET

2019-10-30 21:20 UTC, kq-li commented on app.py
> +        Announcement.expirationDate > datetime.now()
technically there should be a trailing comma here lol

2019-10-30 21:20 UTC, kq-li commented on app.py
> +        return json.dumps({"data": None}), 200
missing success field

2019-10-30 21:20 UTC, kq-li commented on app.py
> +    app.run(host="0.0.0.0", port=5000, debug=True)
turn off debug mode

2019-10-31 01:11 UTC, young-k commented
@seancorc can you mark comments as resolved once they are?

2019-10-31 03:50 UTC, seancorc commented on app.py
> +        Announcement.expirationDate > datetime.now()
Black is deleting it when I try haha.

2019-10-31 18:04 UTC, manishsaha requested changes
thanks for implementing all the changes, just a few more things!

2019-10-31 18:04 UTC, manishsaha commented on app.py
> +    db.session.commit()
announcement* in lines 81, 82 and 84

2019-10-31 18:04 UTC, sahamanish99 commented on app.py
> +        return json.dumps({"success": True, "data": None}), 200
this should just be `“data”: []` for uniformity

2019-10-31 18:04 UTC, sahamanish99 commented on app.py
> +        return json.dumps({"success": True, "data": None}), 200
and then i think u won’t even need this conditional tbh

2019-10-31 19:17 UTC, manishsaha approved these changes
amazing

2019-10-31 19:33 UTC, kq-li approved these changes
sick

2019-10-31 19:33 UTC, kq-li commented on app.py
> +    app.run(host="0.0.0.0", port=environ["PORT"], debug=False)
you can just leave out the debug here

2019-10-31 19:33 UTC, kq-li commented on db.py
> +    __table_name = "announcement"
prefer "announcements"

2019-10-31 19:57 UTC, merged