Add app-specific functionality and refactor
cuappdev/announcements-backend-old pull request #8
Opened 2019-11-10 06:16 UTC by seancorc

## Overview

  
Added app-specific announcement functionality and refactored. The client can now make a request for announcements with their app's name as a url parameter and will get a response containing all active announcements that were created for that app. 
 
 
  ## Changes Made

  
1. I created a new 'apps' table for the database and established a many to many relationship between that table and the 'announcements' table using an association table. If a row for a given validated app name doesn't exist then a row for that app is added to the app table.

2. I created a dao which contains the logic for CRUD operations on the 'announcements' and 'apps' tables.  

  ## Test Coverage

  
I tested the new functionality using postman.
 
 
  ## Next Steps 

  
Next steps are to secure endpoints, add readme with setup instructions, and create documentation.
 
  ## Related PRs or Issues 

  
Git Issue: https://github.com/cuappdev/announcements-backend/issues/7

  ## Example Response For Eatery
Example Response of getting the active announcements for eatery:
```
{
    "success": true,
    "data": [
        {
            "id": 2,
            "body": "body",
            "ctaAction": "action",
            "ctaText": "text",
            "expirationDate": "2019-12-22",
            "includedApps": [
                "eatery"
            ],
            "imageUrl": "url",
            "startDate": "2019-11-01",
            "subject": "sub"
        },
        {
            "id": 4,
            "body": "body",
            "ctaAction": "action",
            "ctaText": "text",
            "expirationDate": "2019-12-22",
            "includedApps": [
                "transit",
                "eatery"
            ],
            "imageUrl": "url",
            "startDate": "2019-11-01",
            "subject": "sub"
        }
    ]
}
```
 
 
  </details>

2019-11-10 06:47 UTC, young-k submitted a review, later dismissed
minor changes, if you fix just dismiss my review, i might not be checking github

2019-11-10 06:47 UTC, young-k commented on Constants.py
> +VALID_APPS = ["pollo", "eatery", "transit", "uplift"]
why is this file not `constants.py`?

2019-11-10 06:47 UTC, young-k commented on Constants.py
> +INVALID_DATE_ERROR = json.dumps({"success": False, "error": "Please input a valid date of the form 'y/m/d'"})
why not `mm/dd/yyyy`?

2019-11-10 06:47 UTC, young-k commented on Constants.py
> +
do we need these newlines everywhere?

2019-11-10 06:47 UTC, young-k commented on app.py
>  import json
python imports should be ordered in the following:

1. default imports
2. library imports
3. local imports

2019-11-10 06:47 UTC, young-k commented on dao.py
> +def getAppByName(name):
why not snakecase?

2019-11-10 06:47 UTC, young-k commented on dao.py
> +def commitAnnouncement(post_body):
all of these should be snakecase

2019-11-10 06:47 UTC, young-k commented on dao.py
> +    if announcement is None:
`if not announcement`

2019-11-10 06:47 UTC, young-k commented on dao.py
> +    if not (all(app in Constants.VALID_APPS for app in includedApps)) or not includedApps:
nifty

2019-11-10 06:47 UTC, young-k commented on dao.py
> +        expiration = valid_date(expirationDate)  # checking for valid date
this comment is redundant, the function name does a good job

2019-11-10 06:47 UTC, young-k commented on dao.py
> +        includedApps = post_body.get("includedApps")
nit, but snakecase variables

2019-11-10 08:37 UTC, kq-li requested changes
solid, +1 to young's and some more stuff

2019-11-10 08:37 UTC, kq-li commented on Constants.py
> +INVALID_ANNOUNCEMENT_ERROR = json.dumps({"success": False, "error": "No announcement with that id exists"})
"Invalid Announcement ID" for consistency? or you can change the others to match this one, either works

2019-11-10 08:37 UTC, kq-li commented on dao.py
> +def valid_date(str):
prefer `is_valid_date`

2019-11-10 08:37 UTC, kq-li commented on dao.py
> +    if not (all(app in Constants.VALID_APPS for app in includedApps)) or not includedApps:
probably need to reverse the order here to check `includedApps` before you iterate it

2019-11-10 08:37 UTC, kq-li commented on dao.py
> +    if not (all(k in (Announcement.__table__.columns + ["includedApps"]) for k in post_body)):
interesting solution, think it might be better to constrain exactly which fields are editable though (for ex this could change the id)

2019-11-10 08:37 UTC, kq-li commented on dao.py
> +            setattr(announcement, k, v)
why not `announcement[k] = v`?

2019-11-10 08:37 UTC, kq-li commented on dao.py
> +    if not (all(k in (Announcement.__table__.columns + ["includedApps"]) for k in post_body)):
also includedApps should already be included in the announcement columns

2019-11-10 19:24 UTC, seancorc commented on dao.py
> +            setattr(announcement, k, v)
Doesn't work

2019-11-10 19:28 UTC, seancorc commented on dao.py
> +            setattr(announcement, k, v)
```announcement[k] = v``` does not work.

2019-11-10 20:30 UTC, alanna-zhou reviewed
looks good :)
just a couple of refactoring nit picks!!!!

2019-11-10 20:30 UTC, alanna-zhou commented on constants.py
> +INVALID_DATE_ERROR = json.dumps({"success": False, "error": "Please input a valid date of the form 'mm/dd/yyyy'"})
would it look cleaner if the errors were separate string constants and you had a function that returned json.dumps given an error string and success boolean?

2019-11-10 20:30 UTC, alanna-zhou commented on dao.py
> +    App.query.filter(App.name == name).first()
in the backend course for sqlalchemy we would do like `filter_by` and `App.name = name` -- y dis so different i curious

2019-11-10 20:30 UTC, alanna-zhou commented on dao.py
> +        expiration = is_valid_date(expiration_date)
these names are a lil vague ? like why would an `expiration_date` become an `expiration` if it was a valid date? also if `is_valid_date` returns a boolean wouldn't it be better if the name reflected that

2019-11-10 20:30 UTC, alanna-zhou commented on dao.py
> +            # setattr(announcement, k, v)
was this accidentally left in here

2019-11-10 21:22 UTC, seancorc commented on dao.py
> +    App.query.filter(App.name == name).first()
They're basically the same thing, but filter allows for more powerful queries using other operators such as '<'. 

https://stackoverflow.com/questions/2128505/whats-the-difference-between-filter-and-filter-by-in-sqlalchemy

2019-11-10 21:23 UTC, seancorc commented on dao.py
> +        expiration = is_valid_date(expiration_date)
'is_valid_date' actually returns the date object so it should be called 'valid_date'. I agree the names are a little vague.

2019-11-10 21:24 UTC, seancorc commented on dao.py
> +            # setattr(announcement, k, v)
Whoops, ya. Nice catch

2019-11-10 21:25 UTC, seancorc commented on dao.py
> +            # setattr(announcement, k, v)
Yup, nice catch

2019-11-10 21:30 UTC, seancorc commented on constants.py
> +INVALID_DATE_ERROR = json.dumps({"success": False, "error": "Please input a valid date of the form 'mm/dd/yyyy'"})
I kind of like returning each error and having them be explicitly written out, but I'm not against creating a function if others think it would be cleaner.

2019-11-11 04:53 UTC, meganle reviewed
looking good! just small things and then we're good to merge

2019-11-11 04:53 UTC, meganle commented on dao.py
> +        appModel = get_app_by_name(app)
snake case so `app_model`

2019-11-11 04:53 UTC, meganle commented on dao.py
> +                return constants.INVAL, 400
which error is this supposed to be?

2019-11-11 06:50 UTC, kq-li approved these changes
some last comments, approving to unblock but just address them before you merge

2019-11-11 06:50 UTC, kq-li commented on constants.py
> +INVALID_DATE_ERROR = json.dumps({"success": False, "error": "Please input a valid date of the form 'mm/dd/yyyy'"})
i prefer this way -- it's cleaner when you actually return the values from the routes

2019-11-11 06:50 UTC, kq-li commented on constants.py
> +INVALID_REQUEST_BODY_ERROR = json.dumps({"success": False, "error": "Invalid Request Body"})
was this changed from before? the cases in these error messages are still inconsistent with each other -- could just lowercase the second and third words here and below

2019-11-11 06:50 UTC, kq-li commented on dao.py
> +            if not (all(app in constants.VALID_APPS for app in v)) or not v:
check `not v` before iterating

2019-11-11 06:50 UTC, kq-li commented on db.py
> +associationTable = db.Table(
`association_table`

2019-11-11 16:20 UTC, meganle approved these changes
once you address Kenneth's comments, it's good to go!

2019-11-11 16:32 UTC, merged